apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: node-deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "sandbox/dev/nodejs"
        objectType: "secretsmanager"
        jmesPath:
          - path: appenv
            objectAlias: appenv
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: aws-secret
      type: Opaque
      data:
        - objectName: appenv
          key: appenv