apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      serviceAccountName: node-deployment-sa
      containers:
      - image: myhk2009/nodetest:20221215-dev-8980823774
        name: nodejs
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        env:
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: appenv
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: node-deployment-spc-k8s-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs