apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prd
namePrefix: prd-
commonLabels:
  env: prd

bases:
- ../../base

patchesStrategicMerge:
- deployment-rollout.yaml
- service-lb.yaml